### ISSUE TITLE
i7z GUI does not compile with gcc-4.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Hypfer/i7z#27]
```
/usr/bin/moc -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED 
-I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore 
-I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. GUI_i7z.cpp -o GUI_i7z.moc
x86_64-pc-linux-gnu-g++ -c -pipe -O2 -pipe -march=corei7 -mcx16 -msahf -mpopcnt 
-msse4.2 --param l1-cache-size=32 --param l1-cache-line-size=64 --param 
l2-cache-size=8192 -mtune=corei7 -frecord-gcc-switches -g 
-Wdisabled-optimization -Wenum-compare -Wall -W -D_REENTRANT -DQT_NO_DEBUG 
-DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. 
-I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. 
-o GUI_i7z.o GUI_i7z.cpp
GUI_i7z.cpp: In function ‘void Construct_Socket_Information_in_GUI(unsigned 
int*)’:
GUI_i7z.cpp:50:52: warning: extended initializer lists only available with 
-std=c++0x or -std=gnu++0x [enabled by default]
GUI_i7z.cpp:50:52: error: assigning to an array from an initializer list
GUI_i7z.cpp:53:52: warning: extended initializer lists only available with 
-std=c++0x or -std=gnu++0x [enabled by default]
GUI_i7z.cpp:53:52: error: assigning to an array from an initializer list

```

Original issue reported on code.google.com by `ju.lec...@googlemail.com` on 21 Apr 2011 at 11:54

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Hi Ju

i just submitted code in SVN that should fix this bug. do tell me if an error 
is still popping up

thanks for the bug report
```

Original comment by `abhirana` on 27 Apr 2011 at 7:29

**Comment by GoogleCodeExporter** [comment]
```
It works fine now. Fix included in Gentoo Linux. Thanks for the fix.
```

Original comment by `ju.lec...@googlemail.com` on 27 Apr 2011 at 7:45

**Comment by GoogleCodeExporter** [comment]
Original comment by `abhirana` on 31 Mar 2012 at 8:27
- Changed state: **Done**
